### ISSUE TITLE
webpack should be done by circleci, and paratii.min.js should not be in git

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-js#200]
we can give it the same treatment as the jsdocs

**Comment by geckoslair** [comment]
Are we sure about that? There's a lot of libs with /dist folder and builded file within....

**Comment by jellegerbrandy** [comment]
My thinking is this:
- paratii.min.js is problematic with merges; building it is slow (on each
commit); it is generated code anyway so no need to keep in in version
control
- the only reason (that I can see) to keep it in git is that in this way it
is available for developers to use, because they can download the compiles
file directly from github.

but perhaps I'm missing a point?

**Comment by geckoslair** [comment]
This is a good reason to keep it in the repo in some way:

"the only reason (that I can see) to keep it in git is that in this way it
is available for developers to use, because they can download the compiles
file directly from github."

If I develop out of webpack (as for the demos repo) i need to access to the min dist from node_modules.
This seems a good approach to our issue:

https://blog.andrewray.me/dealing-with-compiled-files-in-git/

**Comment by geckoslair** [comment]
i've added a .gitattributes file that avoid diff and rebase conflict for dist folder. Please add this driver to your .git/config

[merge "ours"]
    name = "Keep ours merge"
    driver = true
