### ISSUE TITLE
Tests fails in general because TXs stay in pending status on parity waiting for manual confirmation

### ISSUE THREAD

**Issue by geckoslair** [Paratii-Video/paratii-js#271]
Reproduce:
- run parity UI
- run test
- wait for parity signer request in UI

I can check once i'll back the 18th June

**Comment by jellegerbrandy** [comment]
This is (probably) because the contracts have the "from" address set, but that address is not in the wallet (can happen if you give paratii only an address but not a privatekey.

What we should do is that the library never sends out unsigned transactions. This we can do either (quickest way) by simply not allowing that an account is set in paratii without giving the corresponding privatekey or mnemonic. 

(or, in other words, we remove teh "readonly" option from paratii-js, `setAccount` takes as obligory either the privatekey or mnemonic.

**Comment by jellegerbrandy** [comment]
Closing this as no one is complaining anymore :-)
